# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/clynamen/software/projects/ducttape/ducttape-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/clynamen/software/projects/ducttape/ducttape-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/clynamen/software/projects/ducttape/ducttape-engine/CMakeFiles /home/clynamen/software/projects/ducttape/ducttape-engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/clynamen/software/projects/ducttape/ducttape-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BtOgre

# Build rule for target.
BtOgre: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BtOgre
.PHONY : BtOgre

# fast build rule for target.
BtOgre/fast:
	$(MAKE) -f externals/CMakeFiles/BtOgre.dir/build.make externals/CMakeFiles/BtOgre.dir/build
.PHONY : BtOgre/fast

#=============================================================================
# Target rules for targets named OgreProcedural

# Build rule for target.
OgreProcedural: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OgreProcedural
.PHONY : OgreProcedural

# fast build rule for target.
OgreProcedural/fast:
	$(MAKE) -f externals/CMakeFiles/OgreProcedural.dir/build.make externals/CMakeFiles/OgreProcedural.dir/build
.PHONY : OgreProcedural/fast

#=============================================================================
# Target rules for targets named ducttape

# Build rule for target.
ducttape: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ducttape
.PHONY : ducttape

# fast build rule for target.
ducttape/fast:
	$(MAKE) -f engine/CMakeFiles/ducttape.dir/build.make engine/CMakeFiles/ducttape.dir/build
.PHONY : ducttape/fast

#=============================================================================
# Target rules for targets named sample_chat_client

# Build rule for target.
sample_chat_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample_chat_client
.PHONY : sample_chat_client

# fast build rule for target.
sample_chat_client/fast:
	$(MAKE) -f samples/CMakeFiles/sample_chat_client.dir/build.make samples/CMakeFiles/sample_chat_client.dir/build
.PHONY : sample_chat_client/fast

#=============================================================================
# Target rules for targets named sample_chat_server

# Build rule for target.
sample_chat_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample_chat_server
.PHONY : sample_chat_server

# fast build rule for target.
sample_chat_server/fast:
	$(MAKE) -f samples/CMakeFiles/sample_chat_server.dir/build.make samples/CMakeFiles/sample_chat_server.dir/build
.PHONY : sample_chat_server/fast

#=============================================================================
# Target rules for targets named sample_simplepong

# Build rule for target.
sample_simplepong: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample_simplepong
.PHONY : sample_simplepong

# fast build rule for target.
sample_simplepong/fast:
	$(MAKE) -f samples/CMakeFiles/sample_simplepong.dir/build.make samples/CMakeFiles/sample_simplepong.dir/build
.PHONY : sample_simplepong/fast

#=============================================================================
# Target rules for targets named test_connections

# Build rule for target.
test_connections: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_connections
.PHONY : test_connections

# fast build rule for target.
test_connections/fast:
	$(MAKE) -f tests/CMakeFiles/test_connections.dir/build.make tests/CMakeFiles/test_connections.dir/build
.PHONY : test_connections/fast

#=============================================================================
# Target rules for targets named test_display

# Build rule for target.
test_display: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_display
.PHONY : test_display

# fast build rule for target.
test_display/fast:
	$(MAKE) -f tests/CMakeFiles/test_display.dir/build.make tests/CMakeFiles/test_display.dir/build
.PHONY : test_display/fast

#=============================================================================
# Target rules for targets named test_eventbindings

# Build rule for target.
test_eventbindings: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_eventbindings
.PHONY : test_eventbindings

# fast build rule for target.
test_eventbindings/fast:
	$(MAKE) -f tests/CMakeFiles/test_eventbindings.dir/build.make tests/CMakeFiles/test_eventbindings.dir/build
.PHONY : test_eventbindings/fast

#=============================================================================
# Target rules for targets named test_events

# Build rule for target.
test_events: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_events
.PHONY : test_events

# fast build rule for target.
test_events/fast:
	$(MAKE) -f tests/CMakeFiles/test_events.dir/build.make tests/CMakeFiles/test_events.dir/build
.PHONY : test_events/fast

#=============================================================================
# Target rules for targets named test_followpath

# Build rule for target.
test_followpath: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_followpath
.PHONY : test_followpath

# fast build rule for target.
test_followpath/fast:
	$(MAKE) -f tests/CMakeFiles/test_followpath.dir/build.make tests/CMakeFiles/test_followpath.dir/build
.PHONY : test_followpath/fast

#=============================================================================
# Target rules for targets named test_gui

# Build rule for target.
test_gui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_gui
.PHONY : test_gui

# fast build rule for target.
test_gui/fast:
	$(MAKE) -f tests/CMakeFiles/test_gui.dir/build.make tests/CMakeFiles/test_gui.dir/build
.PHONY : test_gui/fast

#=============================================================================
# Target rules for targets named test_input

# Build rule for target.
test_input: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_input
.PHONY : test_input

# fast build rule for target.
test_input/fast:
	$(MAKE) -f tests/CMakeFiles/test_input.dir/build.make tests/CMakeFiles/test_input.dir/build
.PHONY : test_input/fast

#=============================================================================
# Target rules for targets named test_logger

# Build rule for target.
test_logger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_logger
.PHONY : test_logger

# fast build rule for target.
test_logger/fast:
	$(MAKE) -f tests/CMakeFiles/test_logger.dir/build.make tests/CMakeFiles/test_logger.dir/build
.PHONY : test_logger/fast

#=============================================================================
# Target rules for targets named test_mousecursor

# Build rule for target.
test_mousecursor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_mousecursor
.PHONY : test_mousecursor

# fast build rule for target.
test_mousecursor/fast:
	$(MAKE) -f tests/CMakeFiles/test_mousecursor.dir/build.make tests/CMakeFiles/test_mousecursor.dir/build
.PHONY : test_mousecursor/fast

#=============================================================================
# Target rules for targets named test_multiple_camera

# Build rule for target.
test_multiple_camera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_multiple_camera
.PHONY : test_multiple_camera

# fast build rule for target.
test_multiple_camera/fast:
	$(MAKE) -f tests/CMakeFiles/test_multiple_camera.dir/build.make tests/CMakeFiles/test_multiple_camera.dir/build
.PHONY : test_multiple_camera/fast

#=============================================================================
# Target rules for targets named test_music

# Build rule for target.
test_music: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_music
.PHONY : test_music

# fast build rule for target.
test_music/fast:
	$(MAKE) -f tests/CMakeFiles/test_music.dir/build.make tests/CMakeFiles/test_music.dir/build
.PHONY : test_music/fast

#=============================================================================
# Target rules for targets named test_music_fade

# Build rule for target.
test_music_fade: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_music_fade
.PHONY : test_music_fade

# fast build rule for target.
test_music_fade/fast:
	$(MAKE) -f tests/CMakeFiles/test_music_fade.dir/build.make tests/CMakeFiles/test_music_fade.dir/build
.PHONY : test_music_fade/fast

#=============================================================================
# Target rules for targets named test_names

# Build rule for target.
test_names: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_names
.PHONY : test_names

# fast build rule for target.
test_names/fast:
	$(MAKE) -f tests/CMakeFiles/test_names.dir/build.make tests/CMakeFiles/test_names.dir/build
.PHONY : test_names/fast

#=============================================================================
# Target rules for targets named test_network

# Build rule for target.
test_network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_network
.PHONY : test_network

# fast build rule for target.
test_network/fast:
	$(MAKE) -f tests/CMakeFiles/test_network.dir/build.make tests/CMakeFiles/test_network.dir/build
.PHONY : test_network/fast

#=============================================================================
# Target rules for targets named test_particles

# Build rule for target.
test_particles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_particles
.PHONY : test_particles

# fast build rule for target.
test_particles/fast:
	$(MAKE) -f tests/CMakeFiles/test_particles.dir/build.make tests/CMakeFiles/test_particles.dir/build
.PHONY : test_particles/fast

#=============================================================================
# Target rules for targets named test_physics

# Build rule for target.
test_physics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_physics
.PHONY : test_physics

# fast build rule for target.
test_physics/fast:
	$(MAKE) -f tests/CMakeFiles/test_physics.dir/build.make tests/CMakeFiles/test_physics.dir/build
.PHONY : test_physics/fast

#=============================================================================
# Target rules for targets named test_primitive_mesh

# Build rule for target.
test_primitive_mesh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_primitive_mesh
.PHONY : test_primitive_mesh

# fast build rule for target.
test_primitive_mesh/fast:
	$(MAKE) -f tests/CMakeFiles/test_primitive_mesh.dir/build.make tests/CMakeFiles/test_primitive_mesh.dir/build
.PHONY : test_primitive_mesh/fast

#=============================================================================
# Target rules for targets named test_random

# Build rule for target.
test_random: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_random
.PHONY : test_random

# fast build rule for target.
test_random/fast:
	$(MAKE) -f tests/CMakeFiles/test_random.dir/build.make tests/CMakeFiles/test_random.dir/build
.PHONY : test_random/fast

#=============================================================================
# Target rules for targets named test_resourcemanager

# Build rule for target.
test_resourcemanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_resourcemanager
.PHONY : test_resourcemanager

# fast build rule for target.
test_resourcemanager/fast:
	$(MAKE) -f tests/CMakeFiles/test_resourcemanager.dir/build.make tests/CMakeFiles/test_resourcemanager.dir/build
.PHONY : test_resourcemanager/fast

#=============================================================================
# Target rules for targets named test_shadow

# Build rule for target.
test_shadow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_shadow
.PHONY : test_shadow

# fast build rule for target.
test_shadow/fast:
	$(MAKE) -f tests/CMakeFiles/test_shadow.dir/build.make tests/CMakeFiles/test_shadow.dir/build
.PHONY : test_shadow/fast

#=============================================================================
# Target rules for targets named test_signals

# Build rule for target.
test_signals: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_signals
.PHONY : test_signals

# fast build rule for target.
test_signals/fast:
	$(MAKE) -f tests/CMakeFiles/test_signals.dir/build.make tests/CMakeFiles/test_signals.dir/build
.PHONY : test_signals/fast

#=============================================================================
# Target rules for targets named test_sound

# Build rule for target.
test_sound: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sound
.PHONY : test_sound

# fast build rule for target.
test_sound/fast:
	$(MAKE) -f tests/CMakeFiles/test_sound.dir/build.make tests/CMakeFiles/test_sound.dir/build
.PHONY : test_sound/fast

#=============================================================================
# Target rules for targets named test_text

# Build rule for target.
test_text: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_text
.PHONY : test_text

# fast build rule for target.
test_text/fast:
	$(MAKE) -f tests/CMakeFiles/test_text.dir/build.make tests/CMakeFiles/test_text.dir/build
.PHONY : test_text/fast

#=============================================================================
# Target rules for targets named test_timer

# Build rule for target.
test_timer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_timer
.PHONY : test_timer

# fast build rule for target.
test_timer/fast:
	$(MAKE) -f tests/CMakeFiles/test_timer.dir/build.make tests/CMakeFiles/test_timer.dir/build
.PHONY : test_timer/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f docs/CMakeFiles/doc.dir/build.make docs/CMakeFiles/doc.dir/build
.PHONY : doc/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... BtOgre"
	@echo "... OgreProcedural"
	@echo "... ducttape"
	@echo "... sample_chat_client"
	@echo "... sample_chat_server"
	@echo "... sample_simplepong"
	@echo "... test_connections"
	@echo "... test_display"
	@echo "... test_eventbindings"
	@echo "... test_events"
	@echo "... test_followpath"
	@echo "... test_gui"
	@echo "... test_input"
	@echo "... test_logger"
	@echo "... test_mousecursor"
	@echo "... test_multiple_camera"
	@echo "... test_music"
	@echo "... test_music_fade"
	@echo "... test_names"
	@echo "... test_network"
	@echo "... test_particles"
	@echo "... test_physics"
	@echo "... test_primitive_mesh"
	@echo "... test_random"
	@echo "... test_resourcemanager"
	@echo "... test_shadow"
	@echo "... test_signals"
	@echo "... test_sound"
	@echo "... test_text"
	@echo "... test_timer"
	@echo "... doc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

